Making comment on a post
makersacademy/acebook-july2017 pull request #13
Opened 2017-08-22 15:30 UTC by Alexander-Blair

Useful Rails command line commands:

**rails generate model** 
e.g. rails generate model Comment message:text post:references

- Comment is the name of the model
- The message:text defines its attributes
- The post:references sets up the association to the post model

**rails generate controller comments**

---------------
Factory Girl mocks that are created automatically increment the ID, but you can specify the ID along with the message e.g.

let!(:post_0) { create(:post, message: "First post", id: 0) }

If you need additional visibility on Capybara, the following is useful (it shows the page HTML):

p page.body

2017-08-22 16:32 UTC, SaphMB submitted a review, later dismissed

2017-08-22 16:34 UTC, dearshrewdwit requested changes

2017-08-22 16:34 UTC, dearshrewdwit commented on app/controllers/comments_controller.rb
> +    @post = Post.find(params[:post_id].to_i)
can you use rails `params#permit` method

2017-08-22 16:46 UTC, dearshrewdwit requested changes

2017-08-22 16:46 UTC, dearshrewdwit commented on app/controllers/comments_controller.rb
> +    @post = Post.find(params[:post_id].to_i)
Why is using the permit method advised?

 http://api.rubyonrails.org/classes/ActionController/Parameters.html

2017-08-22 16:46 UTC, dearshrewdwit commented on app/controllers/comments_controller.rb
> +    @comment = @post.comments.create(message: params[:comment][:message])
same here

2017-08-22 16:46 UTC, dearshrewdwit commented on app/controllers/comments_controller.rb
> +    @post = Post.find(params[:post_id].to_i)
Think of how to nest your resources: http://guides.rubyonrails.org/routing.html#nested-resources

2017-08-22 16:46 UTC, dearshrewdwit commented on config/routes.rb
> +  resources :comments
Nest the resources:

```ruby
resources :posts do
  resources :comments
end
```

2017-08-22 16:46 UTC, dearshrewdwit commented on spec/factories/comments.rb
> +    post nil
is there a reason `post` is set to nil?

2017-08-22 16:46 UTC, dearshrewdwit commented on spec/features/adding_comments_to_post_spec.rb
> +  let!(:user) { User.create(email: "test@test.com", password: "test12") }
is there a user factory?

2017-08-22 16:46 UTC, dearshrewdwit commented on spec/models/comment_spec.rb
> +    @post = create(:post, message: "Hello")
use `let!` instead of instance variables in a `before` block

2017-08-22 16:46 UTC, dearshrewdwit commented on spec/models/comment_spec.rb
> +    @comment = Comment.new(message: "generic comment", post_id: @post.id)
get factory girl to do this:
Look up traits for a factory: https://robots.thoughtbot.com/never-fear-traits-are-here

```ruby
create(:post, :with_comment)
```

2017-08-23 09:29 UTC, Alexander-Blair commented on app/controllers/comments_controller.rb
> +    @post = Post.find(params[:post_id].to_i)
Done

2017-08-23 09:30 UTC, Alexander-Blair commented on app/controllers/comments_controller.rb
> +    @comment = @post.comments.create(message: params[:comment][:message])
Done

2017-08-23 09:30 UTC, Alexander-Blair commented on config/routes.rb
> +  resources :comments
Done

2017-08-23 09:30 UTC, Alexander-Blair commented on spec/factories/comments.rb
> +    post nil
generated by Rails

2017-08-23 09:30 UTC, Alexander-Blair commented on spec/features/adding_comments_to_post_spec.rb
> +  let!(:user) { User.create(email: "test@test.com", password: "test12") }
Done

2017-08-23 09:30 UTC, Alexander-Blair commented on spec/models/comment_spec.rb
> +    @post = create(:post, message: "Hello")
Done

2017-08-23 09:30 UTC, Alexander-Blair commented on spec/models/comment_spec.rb
> +    @comment = Comment.new(message: "generic comment", post_id: @post.id)
Someone needs to pick this up

2017-08-23 10:00 UTC, dearshrewdwit submitted a review, later dismissed

2017-08-23 10:00 UTC, dearshrewdwit commented on config/routes.rb
> +  resources :posts do
nice

2017-08-23 10:00 UTC, dearshrewdwit commented on spec/controllers/comments_controller_spec.rb
> +  let!(:post_0) { create(:post, message: "First post", id: 0) }
there should be no need declare attributes for this model unless it's integral for an assertion. Let the factory handle it

2017-08-23 10:00 UTC, dearshrewdwit commented on spec/factories/comments.rb
> +FactoryGirl.define do
```ruby
FactoryGirl.define do
   factory :comment do
     message "MyText"
     post  { create(:post) } 
 +  end
 +end
```

2017-08-23 10:00 UTC, dearshrewdwit commented on spec/models/comment_spec.rb
> +    expect(comment.valid?).to eq true
Take advantage of rspec by using the be matchers
```ruby
expect(comment).to be_valid
```

2017-08-23 10:00 UTC, dearshrewdwit commented on spec/models/comment_spec.rb
> +    comment.post_id = nil
use a factory to generate a comment without a post, and use fatory_girl's `#build` to not run validation instead of `#create`

2017-08-23 10:54 UTC, Alexander-Blair commented on spec/controllers/comments_controller_spec.rb
> +  let!(:post_0) { create(:post, message: "First post", id: 0) }
We need the post messages to be distinct in order to ensure the page ordering is correct, I've removed as much flabby code as possible though

2017-08-23 11:13 UTC, dearshrewdwit commented on spec/controllers/comments_controller_spec.rb
> +  let!(:post_0) { create(:post, message: "First post", id: 0) }
How would you get the factory to handle that?
https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#sequences

2017-08-23 11:27 UTC, Alexander-Blair commented on spec/controllers/comments_controller_spec.rb
> +  let!(:post_0) { create(:post, message: "First post", id: 0) }
This should be all tidied up now - just awaiting travis

2017-08-23 13:37 UTC, dearshrewdwit submitted a review, later dismissed
There will likely be merge conflicts with other features implementing the post factory. Be sure to update your branch with master

2017-08-23 14:40 UTC, dearshrewdwit submitted a review, later dismissed

2017-08-23 15:10 UTC, dearshrewdwit approved these changes

2017-08-23 15:10 UTC, merged