Posts have own view
makersacademy/acebook-july2017 pull request #20
Opened 2017-08-23 15:14 UTC by SaphMB

Users can now click on the post body and see the post within a single post view. Single post views have dynamic urls and the user can return to the posts view from a single post view.

Screenshots of post and single post views:
<img width="1280" alt="screen shot 2017-08-23 at 16 11 33" src="https://user-images.githubusercontent.com/9513073/29623354-010fee76-881e-11e7-8925-c347e9d18b2d.png">
<img width="1151" alt="screen shot 2017-08-23 at 16 13 07" src="https://user-images.githubusercontent.com/9513073/29623353-0109e13e-881e-11e7-9c94-23d4bfd325dd.png">

2017-08-23 16:05 UTC, dearshrewdwit requested changes

2017-08-23 16:05 UTC, dearshrewdwit commented on app/controllers/posts_controller.rb
> +	def show
indentation

2017-08-23 16:05 UTC, dearshrewdwit commented on app/views/posts/index.html.erb
> +		<a class="body_link" href="/posts/<%=post.id%>">
indentation

2017-08-24 11:26 UTC, artemisxen commented
@dearshrewdwit conflicts resolved. Can you review please?

2017-08-24 11:30 UTC, dearshrewdwit requested changes

2017-08-24 11:30 UTC, dearshrewdwit commented on spec/features/user-can-view-post-at-its-dynamic-url.rb
> +    visit "/posts/1"
this should be a helper path method

2017-08-24 11:30 UTC, dearshrewdwit commented on spec/features/user-can-view-post-at-its-dynamic-url.rb
> +    visit "/posts/1"
`post_path(post)` something like

2017-08-24 11:30 UTC, dearshrewdwit commented on app/views/posts/index.html.erb
> +	<a class="body_link" href="/posts/<%=post.id%>"> posted at: <%= post.posted_at %></a>
this should be a helper method like `post_path(post)`

2017-08-24 12:04 UTC, artemisxen commented
@dearshrewdwit updated

2017-08-24 15:50 UTC, artemisxen commented
@dearshrewdwit test passed

2017-08-25 10:45 UTC, dearshrewdwit submitted a review, later dismissed

2017-08-25 11:04 UTC, closed without merging