add name to post
makersacademy/acebook-july2017 pull request #24
Opened 2017-08-23 17:16 UTC by adoolaeghe

2017-08-23 17:50 UTC, dearshrewdwit requested changes

2017-08-23 17:50 UTC, dearshrewdwit commented on app/views/posts/index.html.erb
> +        <%= post.user.first_name %> <%=post.user.last_name  %>
Is there a way to make this code simpler? What is the object that you need for the names? How could you pass it in?

2017-08-23 17:54 UTC, adoolaeghe commented on app/views/posts/index.html.erb
> +        <%= post.user.first_name %> <%=post.user.last_name  %>
<%= post.user.first_name + " " + post.user.last_name  %> ???

2017-08-23 18:20 UTC, dearshrewdwit requested changes

2017-08-23 18:20 UTC, dearshrewdwit commented on app/models/post.rb
> +    return user.first_name
How does implicit return in Ruby work?

2017-08-23 18:20 UTC, dearshrewdwit commented on app/models/post.rb
> +    return user.first_name
How does implicit return in Ruby work?

2017-08-23 18:20 UTC, dearshrewdwit commented on app/views/posts/index.html.erb
> +        <%= post.first_name + " " + post.last_name  %>
If this is the intended output, maybe use one method on the model that returns the full name?

And TEST it 🎉

2017-08-24 10:45 UTC, dearshrewdwit requested changes

2017-08-24 10:45 UTC, dearshrewdwit commented on app/models/post.rb
> +    user.first_name + user.last_name
where is the test for this?

2017-08-24 10:45 UTC, dearshrewdwit commented
remember to write a description of the PR

2017-08-24 11:20 UTC, dearshrewdwit submitted a review, later dismissed

2017-08-24 11:20 UTC, dearshrewdwit commented on app/models/post.rb
> +    "#{user.first_name} #{user.last_name}"
👍

2017-08-24 11:20 UTC, dearshrewdwit commented
@adoolaeghe please remember to fill out the description of your PRs

2017-08-24 11:22 UTC, tobold commented
Please don't merge this until the database has been migrated to remove NULL:
https://github.com/makersacademy/acebook-july2017/pull/28

2017-08-24 14:31 UTC, tobold approved these changes
simply rebasing, old review still applies

2017-08-24 14:32 UTC, merged